### ISSUE TITLE
Replace grunt with gulp

### ISSUE THREAD

**Issue by maxfelker** [BigRoomStudios/angular-admin#5]
We're looking to move away from `grunt` and towards `gulp`. We would like gulp to be in charge of all the tasks grunt is currently responsible for including running the app, build processes and testing.

**Comment by jdonisvitch** [comment]
@maxatbrs -- I have this mostly done. Just need to resolve issues with testing the isolatedScope... Hook me up with perms to push to this repo!

**Comment by jdonisvitch** [comment]
https://github.com/maxatbrs/angular-admin/pull/14

**Comment by maxfelker** [comment]
Merged in with #14
